# Generated by Django 4.2 on 2026-05-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.URLField(verbose_name='URL da Imagem')),
                ('github_url', models.URLField(verbose_name='URL do GitHub')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='URL ao Vivo')),
                ('technologies', models.JSONField(default=list, verbose_name='Tecnologias')),
                ('date_created', models.DateField(verbose_name='Data de Criação')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-date_created'],
            },
        ),
    ]
