# Generated by Django 4.2 on 2026-05-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cargo/Título')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa/Instituição')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('type_of_experience', models.CharField(choices=[('work', 'Trabalho'), ('education', 'Educação'), ('certification', 'Certificação')], default='work', max_length=20, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('is_current', models.BooleanField(default=False, verbose_name='Atual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['-start_date'],
            },
        ),
    ]
